# Generated by Django 3.0 on 2020-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
